export function xpForLevel(level) { return Math.floor(100 * Math.pow(level, 1.5)) }
export function levelFromXp(xp) {
  let level = 1, remaining = xp
  while (remaining >= xpForLevel(level)) { remaining -= xpForLevel(level); level++ }
  return { level, currentLevelXp: remaining, nextLevelXp: xpForLevel(level), progress: remaining / xpForLevel(level) }
}
export const XP_REWARDS = { task_complete: 20, task_hard: 35, pomodoro: 15, study_session: 10, daily_login: 5, flashcard_review: 5, friend_add: 30, group_session: 25, note_share: 15, note_like: 5 }
export const ACHIEVEMENT_DEFS = [
  { key: 'first_task', title: 'First Steps', desc: 'Complete your first task', icon: '🎯' },
  { key: 'first_session', title: 'Getting Started', desc: 'Complete a study session', icon: '📚' },
  { key: 'streak_3', title: 'On Fire', desc: '3-day study streak', icon: '🔥' },
  { key: 'streak_7', title: 'Week Warrior', desc: '7-day study streak', icon: '⚡' },
  { key: 'streak_30', title: 'Unstoppable', desc: '30-day study streak', icon: '🚀' },
  { key: 'tasks_10', title: 'Task Master', desc: 'Complete 10 tasks', icon: '✅' },
  { key: 'tasks_50', title: 'Productivity Beast', desc: 'Complete 50 tasks', icon: '💪' },
  { key: 'hours_10', title: 'Scholar', desc: 'Study 10 total hours', icon: '🎓' },
  { key: 'hours_50', title: 'Dedicated', desc: 'Study 50 total hours', icon: '📖' },
  { key: 'level_5', title: 'Rising Star', desc: 'Reach level 5', icon: '⭐' },
  { key: 'level_10', title: 'Legend', desc: 'Reach level 10', icon: '👑' },
  { key: 'pomodoro_10', title: 'Focus Master', desc: 'Complete 10 pomodoros', icon: '🍅' },
  { key: 'tasks_5', title: 'Getting Things Done', desc: 'Complete 5 tasks', icon: '📋' },
  { key: 'tasks_25', title: 'Quarter Century', desc: 'Complete 25 tasks', icon: '📝' },
  { key: 'tasks_100', title: 'Centurion', desc: 'Complete 100 tasks', icon: '🏆' },
  { key: 'tasks_250', title: 'Task Titan', desc: 'Complete 250 tasks', icon: '🗿' },
  { key: 'tasks_500', title: 'Task God', desc: 'Complete 500 tasks', icon: '⚡' },
  { key: 'tasks_1000', title: 'Unreal', desc: 'Complete 1000 tasks', icon: '💎' },
  { key: 'streak_2', title: 'Double Up', desc: '2-day study streak', icon: '✌️' },
  { key: 'streak_5', title: 'Almost a Week', desc: '5-day study streak', icon: '🌟' },
  { key: 'streak_10', title: 'Perfect Ten', desc: '10-day study streak', icon: '🔟' },
  { key: 'streak_14', title: 'Fortnight', desc: '14-day study streak', icon: '🌙' },
  { key: 'streak_21', title: 'Habit Former', desc: '21-day study streak', icon: '🧠' },
  { key: 'streak_50', title: 'Iron Will', desc: '50-day study streak', icon: '🛡️' },
  { key: 'streak_60', title: 'Two Months Strong', desc: '60-day study streak', icon: '📅' },
  { key: 'streak_90', title: 'Quarter Year', desc: '90-day study streak', icon: '⏰' },
  { key: 'streak_100', title: 'Triple Digits', desc: '100-day study streak', icon: '💯' },
  { key: 'streak_180', title: 'Half a Year', desc: '180-day study streak', icon: '📆' },
  { key: 'streak_365', title: 'Full Year', desc: '365-day study streak', icon: '🎊' },
  { key: 'hours_1', title: 'First Hour', desc: 'Study 1 total hour', icon: '🕐' },
  { key: 'hours_5', title: 'Warming Up', desc: 'Study 5 total hours', icon: '⏱️' },
  { key: 'hours_25', title: 'Deep Diver', desc: 'Study 25 total hours', icon: '🌊' },
  { key: 'hours_100', title: 'Century Club', desc: 'Study 100 total hours', icon: '🏅' },
  { key: 'hours_250', title: 'Time Lord', desc: 'Study 250 total hours', icon: '⌛' },
  { key: 'hours_500', title: 'Marathon Mind', desc: 'Study 500 total hours', icon: '🏃' },
  { key: 'hours_1000', title: 'Time Immortal', desc: 'Study 1000 total hours', icon: '♾️' },
  { key: 'level_2', title: 'Climbing', desc: 'Reach level 2', icon: '📈' },
  { key: 'level_3', title: 'Gaining Momentum', desc: 'Reach level 3', icon: '🚀' },
  { key: 'level_4', title: 'Finding Your Groove', desc: 'Reach level 4', icon: '🎵' },
  { key: 'level_6', title: 'Power Player', desc: 'Reach level 6', icon: '🎮' },
  { key: 'level_7', title: 'Lucky Seven', desc: 'Reach level 7', icon: '🎲' },
  { key: 'level_8', title: 'Great Eight', desc: 'Reach level 8', icon: '🎱' },
  { key: 'level_9', title: 'Cloud Nine', desc: 'Reach level 9', icon: '☁️' },
  { key: 'level_15', title: 'Elite', desc: 'Reach level 15', icon: '🎖️' },
  { key: 'level_20', title: 'Grandmaster', desc: 'Reach level 20', icon: '♟️' },
  { key: 'level_25', title: 'Mythic', desc: 'Reach level 25', icon: '🔮' },
  { key: 'level_30', title: 'Ascended', desc: 'Reach level 30', icon: '🪐' },
  { key: 'level_50', title: 'Transcendent', desc: 'Reach level 50', icon: '🌌' },
  { key: 'pomodoro_1', title: 'First Tomato', desc: 'Complete 1 pomodoro', icon: '🍅' },
  { key: 'pomodoro_5', title: 'Tomato Squad', desc: 'Complete 5 pomodoros', icon: '🥫' },
  { key: 'pomodoro_25', title: 'Tomato Garden', desc: 'Complete 25 pomodoros', icon: '🌱' },
  { key: 'pomodoro_50', title: 'Tomato Farm', desc: 'Complete 50 pomodoros', icon: '🚜' },
  { key: 'pomodoro_100', title: 'Tomato Empire', desc: 'Complete 100 pomodoros', icon: '🏛️' },
  { key: 'pomodoro_250', title: 'Tomato Tycoon', desc: 'Complete 250 pomodoros', icon: '💼' },
  { key: 'pomodoro_500', title: 'Sauce Baron', desc: 'Complete 500 pomodoros', icon: '🍝' },
  { key: 'fc_10', title: 'Card Collector', desc: 'Create 10 flashcards', icon: '🃏' },
  { key: 'fc_50', title: 'Card Shark', desc: 'Create 50 flashcards', icon: '🦈' },
  { key: 'fc_100', title: 'Card Master', desc: 'Create 100 flashcards', icon: '🎴' },
  { key: 'fc_250', title: 'Card Library', desc: 'Create 250 flashcards', icon: '📚' },
  { key: 'fc_500', title: 'Card Archive', desc: 'Create 500 flashcards', icon: '🗂️' },
  { key: 'fc_review_10', title: 'Quick Reviewer', desc: 'Review 10 flashcards', icon: '👁️' },
  { key: 'fc_review_50', title: 'Diligent Reviewer', desc: 'Review 50 flashcards', icon: '🔍' },
  { key: 'fc_review_100', title: 'Review Pro', desc: 'Review 100 flashcards', icon: '🔬' },
  { key: 'fc_review_500', title: 'Memory Palace', desc: 'Review 500 flashcards', icon: '🏰' },
  { key: 'notes_5', title: 'Note Taker', desc: 'Create 5 notes', icon: '✏️' },
  { key: 'notes_25', title: 'Note Keeper', desc: 'Create 25 notes', icon: '📝' },
  { key: 'notes_50', title: 'Notebook Master', desc: 'Create 50 notes', icon: '📓' },
  { key: 'notes_100', title: 'Archivist', desc: 'Create 100 notes', icon: '🗃️' },
  { key: 'notes_250', title: 'Wordsmith', desc: 'Create 250 notes', icon: '✒️' },
  { key: 'subjects_1', title: 'First Subject', desc: 'Create your first subject', icon: '📘' },
  { key: 'subjects_3', title: 'Triple Threat', desc: 'Create 3 subjects', icon: '📚' },
  { key: 'subjects_5', title: 'Well Rounded', desc: 'Create 5 subjects', icon: '🎓' },
  { key: 'subjects_8', title: 'Renaissance Student', desc: 'Create 8 subjects', icon: '🎨' },
  { key: 'subjects_10', title: 'Polymath', desc: 'Create 10 subjects', icon: '🧠' },
  { key: 'exams_1', title: 'Exam Ready', desc: 'Add your first exam', icon: '📋' },
  { key: 'exams_5', title: 'Exam Veteran', desc: 'Add 5 exams', icon: '🛡️' },
  { key: 'exams_10', title: 'Exam Survivor', desc: 'Add 10 exams', icon: '⚔️' },
  { key: 'exams_20', title: 'Exam Conqueror', desc: 'Add 20 exams', icon: '🗡️' },
  { key: 'session_1', title: 'First Session', desc: 'Log your first study session', icon: '🕐' },
  { key: 'session_10', title: 'Regular', desc: 'Log 10 study sessions', icon: '📅' },
  { key: 'session_25', title: 'Consistent', desc: 'Log 25 study sessions', icon: '📌' },
  { key: 'session_50', title: 'Dedicated Student', desc: 'Log 50 study sessions', icon: '🎯' },
  { key: 'session_100', title: 'Study Machine', desc: 'Log 100 study sessions', icon: '🤖' },
  { key: 'session_250', title: 'Unbreakable', desc: 'Log 250 study sessions', icon: '🦾' },
  { key: 'session_500', title: 'Study Legend', desc: 'Log 500 study sessions', icon: '🌟' },
  { key: 'daily_goal_1', title: 'Goal Getter', desc: 'Hit your daily goal once', icon: '✅' },
  { key: 'daily_goal_7', title: 'Weekly Achiever', desc: 'Hit your daily goal 7 times', icon: '📆' },
  { key: 'daily_goal_30', title: 'Monthly Master', desc: 'Hit your daily goal 30 times', icon: '🏆' },
  { key: 'daily_goal_100', title: 'Goal Crusher', desc: 'Hit your daily goal 100 times', icon: '💥' },
  { key: 'early_bird', title: 'Early Bird', desc: 'Study before 7 AM', icon: '🐦' },
  { key: 'night_owl', title: 'Night Owl', desc: 'Study after midnight', icon: '🦉' },
  { key: 'weekend_warrior', title: 'Weekend Warrior', desc: 'Study on a Saturday', icon: '🎉' },
  { key: 'sunday_scholar', title: 'Sunday Scholar', desc: 'Study on a Sunday', icon: '☀️' },
  { key: 'marathon_2h', title: 'Two Hour Marathon', desc: 'Study 2 hours in one session', icon: '🏃' },
  { key: 'marathon_4h', title: 'Four Hour Marathon', desc: 'Study 4 hours in one session', icon: '🏃‍♂️' },
  { key: 'marathon_6h', title: 'Iron Student', desc: 'Study 6 hours in one session', icon: '🦿' },
  { key: 'all_subjects', title: 'Renaissance', desc: 'Study all subjects in one day', icon: '🎭' },
  { key: 'high_priority_5', title: 'Priority Player', desc: 'Complete 5 high-priority tasks', icon: '🔴' },
  { key: 'high_priority_25', title: 'Priority Pro', desc: 'Complete 25 high-priority tasks', icon: '⚡' },
  { key: 'high_priority_50', title: 'Priority Master', desc: 'Complete 50 high-priority tasks', icon: '🔥' },
  { key: 'hard_task_5', title: 'Hard Worker', desc: 'Complete 5 hard tasks', icon: '💪' },
  { key: 'hard_task_25', title: 'Hard Hitter', desc: 'Complete 25 hard tasks', icon: '🥊' },
  { key: 'hard_task_50', title: 'Hardcore', desc: 'Complete 50 hard tasks', icon: '🪨' },
  { key: 'perfect_day', title: 'Perfect Day', desc: 'Complete all tasks in a day', icon: '🌟' },
  { key: 'perfect_week', title: 'Perfect Week', desc: 'Complete all tasks for 7 days straight', icon: '💎' },
  { key: 'comeback', title: 'Comeback Kid', desc: 'Study after a 3+ day break', icon: '🔄' },
  { key: 'no_break_3h', title: 'In The Zone', desc: 'Study 3 hours without a break', icon: '🎯' },
  { key: 'files_1', title: 'File First', desc: 'Upload your first file', icon: '📎' },
  { key: 'files_10', title: 'File Collector', desc: 'Upload 10 files', icon: '📁' },
  { key: 'files_50', title: 'File Organizer', desc: 'Upload 50 files', icon: '🗂️' },
  { key: 'files_100', title: 'File Master', desc: 'Upload 100 files', icon: '📦' },
  { key: 'xp_100', title: 'Century XP', desc: 'Earn 100 XP', icon: '💯' },
  { key: 'xp_500', title: 'XP Enthusiast', desc: 'Earn 500 XP', icon: '🌟' },
  { key: 'xp_1000', title: 'XP Hunter', desc: 'Earn 1000 XP', icon: '⚡' },
  { key: 'xp_5000', title: 'XP Grinder', desc: 'Earn 5000 XP', icon: '⚔️' },
  { key: 'xp_10000', title: 'XP Millionaire', desc: 'Earn 10000 XP', icon: '💰' },
  { key: 'xp_50000', title: 'XP Demigod', desc: 'Earn 50000 XP', icon: '🔱' },
  { key: 'quiz_perfect_10', title: 'Perfect Quiz', desc: 'Get 10/10 in a flashcard quiz', icon: '🎓' },
  { key: 'quiz_perfect_25', title: 'Quiz Champion', desc: 'Get 25/25 in a flashcard quiz', icon: '🥇' },
  { key: 'quiz_perfect_50', title: 'Quiz Legend', desc: 'Get 50/50 in a flashcard quiz', icon: '👑' },
  { key: 'star_10', title: 'Star Collector', desc: 'Star 10 flashcards', icon: '⭐' },
  { key: 'star_25', title: 'Star Gazer', desc: 'Star 25 flashcards', icon: '✨' },
  { key: 'star_50', title: 'Starstruck', desc: 'Star 50 flashcards', icon: '🌠' },
  { key: 'pin_5', title: 'Pinned', desc: 'Pin 5 notes', icon: '📌' },
  { key: 'pin_20', title: 'Pin Master', desc: 'Pin 20 notes', icon: '📍' },
  { key: 'favorite_5', title: 'Favorites', desc: 'Favorite 5 notes', icon: '❤️' },
  { key: 'favorite_20', title: 'Collector', desc: 'Favorite 20 notes', icon: '💖' },
  { key: 'theme_1', title: 'Style Conscious', desc: 'Change your theme', icon: '🎨' },
  { key: 'theme_5', title: 'Theme Explorer', desc: 'Try 5 different themes', icon: '🎭' },
  { key: 'theme_all', title: 'Theme Tourist', desc: 'Try all 10 themes', icon: '🌈' },
  { key: 'custom_color', title: 'Customizer', desc: 'Set a custom primary color', icon: '🖌️' },
  { key: 'avatar_change', title: 'New Look', desc: 'Change your avatar', icon: '🎭' },
  { key: 'username_change', title: 'Identity', desc: 'Change your username', icon: '🪪' },
  { key: 'goal_30min', title: 'Goal Setter', desc: 'Set a daily study goal', icon: '🎯' },
  { key: 'goal_120min', title: 'Ambitious', desc: 'Set a 2-hour daily goal', icon: '🚀' },
  { key: 'goal_300min', title: 'Overachiever', desc: 'Set a 5-hour daily goal', icon: '💪' },
  { key: 'focus_25', title: 'Classic Focus', desc: 'Complete a 25-minute focus session', icon: '🍅' },
  { key: 'focus_45', title: 'Deep Focus', desc: 'Complete a 45-minute focus session', icon: '🧘' },
  { key: 'focus_60', title: 'Ultra Focus', desc: 'Complete a 60-minute focus session', icon: '⚡' },
  { key: 'focus_90', title: 'Zen Master', desc: 'Complete a 90-minute focus session', icon: '🧓' },
  { key: 'stopwatch_30', title: 'Time Tracker', desc: 'Use stopwatch for 30 minutes', icon: '⏱️' },
  { key: 'countdown_60', title: 'Deadline Driven', desc: 'Use countdown for 60 minutes', icon: '⏳' },
  { key: 'new_year', title: 'New Year Resolution', desc: 'Study on January 1st', icon: '🎉' },
  { key: 'midnight_study', title: 'Midnight Oil', desc: 'Study at exactly midnight', icon: '🕯️' },
  { key: 'dawn_study', title: 'Dawn Patrol', desc: 'Study at 5 AM', icon: '🌅' },
  { key: 'holiday_study', title: 'Holiday Hustler', desc: 'Study on a holiday', icon: '🎄' },
  { key: 'rainy_day', title: 'Rainy Day', desc: 'Study while it rains', icon: '🌧️' },
  { key: 'monday_motivation', title: 'Monday Motivation', desc: 'Study on a Monday', icon: '💪' },
  { key: 'friday_focus', title: 'Friday Focus', desc: 'Study on a Friday', icon: '🎯' },
  { key: 'study_5_days', title: 'Work Week', desc: 'Study 5 days in one week', icon: '📅' },
  { key: 'study_7_days', title: 'Full Week', desc: 'Study all 7 days in one week', icon: '🗓️' },
  { key: 'back_to_back', title: 'Back to Back', desc: 'Complete 2 study sessions in one day', icon: '🔁' },
  { key: 'triple_session', title: 'Triple Threat', desc: 'Complete 3 sessions in one day', icon: '🎯' },
  { key: 'quick_note_5', title: 'Quick Thinker', desc: 'Create 5 quick notes', icon: '💭' },
  { key: 'quick_note_25', title: 'Quick Mind', desc: 'Create 25 quick notes', icon: '🧠' },
  { key: 'quick_note_50', title: 'Quick Draw', desc: 'Create 50 quick notes', icon: '⚡' },
  { key: 'subject_time_1h', title: 'Subject Scholar', desc: 'Study 1 hour in one subject', icon: '📘' },
  { key: 'subject_time_5h', title: 'Subject Expert', desc: 'Study 5 hours in one subject', icon: '📗' },
  { key: 'subject_time_10h', title: 'Subject Master', desc: 'Study 10 hours in one subject', icon: '📕' },
  { key: 'subject_time_25h', title: 'Subject Authority', desc: 'Study 25 hours in one subject', icon: '📙' },
  { key: 'subject_time_50h', title: 'Subject Legend', desc: 'Study 50 hours in one subject', icon: '📚' },
  { key: 'all_tasks_week', title: 'Task Terminator', desc: 'Complete 20 tasks in one week', icon: '🤖' },
  { key: 'all_tasks_month', title: 'Productivity King', desc: 'Complete 50 tasks in one month', icon: '👑' },
  { key: 'first_week', title: 'First Week', desc: 'Study every day in your first week', icon: '🎉' },
  { key: 'first_month', title: 'First Month', desc: 'Study 20+ days in your first month', icon: '🏆' },
  { key: 'level_100', title: 'Max Level', desc: 'Reach level 100', icon: '🌌' },
  { key: 'streak_500', title: 'Unbreakable Streak', desc: '500-day study streak', icon: '🛡️' },
  { key: 'hours_5000', title: '5000 Hour Club', desc: 'Study 5000 total hours', icon: '⏰' },
  { key: 'tasks_5000', title: 'Task Phenomenon', desc: 'Complete 5000 tasks', icon: '🌟' },
  { key: 'fc_1000', title: 'Card Encyclopedia', desc: 'Create 1000 flashcards', icon: '📖' },
  { key: 'notes_500', title: 'Master Librarian', desc: 'Create 500 notes', icon: '🏛️' },
  { key: 'sessions_1000', title: 'Eternal Student', desc: 'Log 1000 study sessions', icon: '♾️' },
  { key: 'quiz_master_100', title: 'Quiz God', desc: 'Get 100 perfect quizzes', icon: '👑' },
  { key: 'completionist', title: 'Completionist', desc: 'Unlock 100 achievements', icon: '🎖️' },
  { key: 'halfway_there', title: 'Halfway There', desc: 'Unlock 75 achievements', icon: '🎯' },
  { key: 'quarter_done', title: 'Quarter Done', desc: 'Unlock 40 achievements', icon: '📊' },
  { key: 'getting_started_ach', title: 'Achievement Hunter', desc: 'Unlock 10 achievements', icon: '🔍' },
  { key: 'collector', title: 'Collector', desc: 'Unlock 25 achievements', icon: '📦' },
  { key: 'enthusiast', title: 'Enthusiast', desc: 'Unlock 50 achievements', icon: '🏆' },
  { key: 'first_friend', title: 'First Friend', desc: 'Add your first friend', icon: '👥' },
  { key: 'study_together', title: 'Study Together', desc: 'Join a group study session', icon: '🤝' },
  { key: 'shared_knowledge', title: 'Shared Knowledge', desc: 'Share your first note', icon: '📤' },
  { key: 'top_10_leaderboard', title: 'Top 10', desc: 'Reach top 10 on a leaderboard', icon: '🏅' },
  { key: 'team_player', title: 'Team Player', desc: 'Complete 5 group sessions', icon: '🤝' },
  { key: 'study_partner', title: 'Consistent Study Partner', desc: 'Study with the same friend 10 times', icon: '🫂' },
  { key: 'social_butterfly', title: 'Social Butterfly', desc: 'Add 10 friends', icon: '🦋' },
  { key: 'note_liked', title: 'Crowd Favorite', desc: 'Get a like on your shared note', icon: '❤️' },
  { key: 'note_downloaded', title: 'Helping Hand', desc: 'Get a note duplicated by someone', icon: '📥' },
  { key: 'popular_note', title: 'Viral Knowledge', desc: 'Get 10 likes on a shared note', icon: '🔥' },
  { key: 'trending_note', title: 'Trending', desc: 'Have a note featured in trending', icon: '📈' },
]
export function formatDate(dateStr) {
  if (!dateStr) return ''
  const d = new Date(dateStr), today = new Date(); today.setHours(0,0,0,0)
  const diff = Math.round((d - today) / (1000*60*60*24))
  if (diff === 0) return 'Today'; if (diff === 1) return 'Tomorrow'; if (diff === -1) return 'Yesterday'
  if (diff < 0) return `${Math.abs(diff)}d overdue`; if (diff <= 7) return `In ${diff}d`
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}
export function todayStr() { return new Date().toISOString().split('T')[0] }
export function getStreak(sessions) {
  if (!sessions || sessions.length === 0) return 0
  const dates = [...new Set(sessions.map(s => s.session_date))].sort().reverse()
  const today = new Date(); today.setHours(0,0,0,0)
  let streak = 0, checkDate = new Date(today)
  for (const dateStr of dates) {
    const d = new Date(dateStr + 'T00:00:00')
    if (d.getTime() === checkDate.getTime()) { streak++; checkDate.setDate(checkDate.getDate() - 1) }
    else if (d < checkDate) break
  }
  return streak
}
export const PRIORITY_CONFIG = {
  high: { label: 'High', color: '#ef4444', bg: '#fee8e8' },
  medium: { label: 'Medium', color: '#f59e0b', bg: '#fef4e6' },
  low: { label: 'Low', color: '#22c55e', bg: '#e8f9ee' },
}
export const DIFFICULTY_CONFIG = {
  easy: { label: 'Easy', color: '#22c55e', bg: '#e8f9ee', xp: 15 },
  medium: { label: 'Medium', color: '#f59e0b', bg: '#fef4e6', xp: 25 },
  hard: { label: 'Hard', color: '#ef4444', bg: '#fee8e8', xp: 40 },
}
export const SUBJECT_ICONS = ['📘','🧮','⚗️','🧬','📖','🇮🇳','🇫🇷','💻','🌍','🎨','🎵','🏛️','📐','🔬','✏️','🧪']
export const SUBJECT_COLORS = ['#4f7cff','#22c55e','#f59e0b','#ec4899','#8b5cf6','#06b6d4','#ef4444','#14b8a6','#f97316','#6366f1']
export const AVATAR_OPTIONS = ['🦊','🐱','🐼','🦉','🦁','🐸','🐙','🦄','🐯','🐨','🐲','🤖','👻','🌟','🔥','🚀']
export const THEMES = {
  default: { name: 'Default', bg: '#f7f8fc', surface: '#ffffff', text: '#1a1f36', text2: '#5a6378', border: '#e2e6ef', sidebar: '#ffffff', dark: false },
  light: { name: 'Light', bg: '#f9fafb', surface: '#ffffff', text: '#111827', text2: '#6b7280', border: '#e5e7eb', sidebar: '#ffffff', dark: false },
  dark: { name: 'Dark', bg: '#0f1117', surface: '#1a1d28', text: '#e4e7ec', text2: '#8b919e', border: '#2a2e3c', sidebar: '#161822', dark: true },
  amoled: { name: 'AMOLED', bg: '#000000', surface: '#0a0a0a', text: '#e4e7ec', text2: '#8b919e', border: '#1a1a1a', sidebar: '#000000', dark: true },
  neon: { name: 'Neon', bg: '#0a0a1a', surface: '#12122a', text: '#00ff9f', text2: '#6666aa', border: '#2a2a4a', sidebar: '#0a0a1a', dark: true },
  cyberpunk: { name: 'Cyberpunk', bg: '#0d0221', surface: '#1a0b3d', text: '#ff006e', text2: '#9d4edd', border: '#3a0ca3', sidebar: '#0d0221', dark: true },
  ocean: { name: 'Ocean', bg: '#e6f0fa', surface: '#ffffff', text: '#0a3d62', text2: '#3c6382', border: '#b3d9f2', sidebar: '#d4e9f7', dark: false },
  matrix: { name: 'Matrix', bg: '#000800', surface: '#001a00', text: '#00ff00', text2: '#008800', border: '#003300', sidebar: '#000800', dark: true },
  glass: { name: 'Glass', bg: '#e8ecf4', surface: '#ffffff', text: '#1a1f36', text2: '#5a6378', border: '#d0d8e8', sidebar: '#ffffff', dark: false },
  minimal: { name: 'Minimal', bg: '#fafafa', surface: '#ffffff', text: '#1a1a1a', text2: '#999999', border: '#eaeaea', sidebar: '#ffffff', dark: false },
}
